/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { InlineResponse404 } from '../model/inlineResponse404';
import { PastExamsHubCoreApplicationCoursesCommandsCreateCreateCourseCommand } from '../model/pastExamsHubCoreApplicationCoursesCommandsCreateCreateCourseCommand';
import { PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommand } from '../model/pastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommand';
import { PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommandResult } from '../model/pastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommandResult';
import { PastExamsHubCoreApplicationCoursesCommandsUpdateUpdateCourseCommand } from '../model/pastExamsHubCoreApplicationCoursesCommandsUpdateUpdateCourseCommand';
import { PastExamsHubCoreApplicationCoursesQueriesGetCollectionGetCoursesQueryResult } from '../model/pastExamsHubCoreApplicationCoursesQueriesGetCollectionGetCoursesQueryResult';
import { PastExamsHubCoreApplicationCoursesQueriesGetSingleGetCourseQueryResult } from '../model/pastExamsHubCoreApplicationCoursesQueriesGetSingleGetCourseQueryResult';
import { PastExamsHubCoreDomainEnumsCourseType } from '../model/pastExamsHubCoreDomainEnumsCourseType';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CoursesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param studyYear 
     * @param filterTeacherUid 
     * @param filterType 
     * @param pageNumber 
     * @param pageSize 
     * @param searchText 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public coursesGet(studyYear?: number, filterTeacherUid?: string, filterType?: PastExamsHubCoreDomainEnumsCourseType, pageNumber?: number, pageSize?: number, searchText?: string, observe?: 'body', reportProgress?: boolean): Observable<PastExamsHubCoreApplicationCoursesQueriesGetCollectionGetCoursesQueryResult>;
    public coursesGet(studyYear?: number, filterTeacherUid?: string, filterType?: PastExamsHubCoreDomainEnumsCourseType, pageNumber?: number, pageSize?: number, searchText?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PastExamsHubCoreApplicationCoursesQueriesGetCollectionGetCoursesQueryResult>>;
    public coursesGet(studyYear?: number, filterTeacherUid?: string, filterType?: PastExamsHubCoreDomainEnumsCourseType, pageNumber?: number, pageSize?: number, searchText?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PastExamsHubCoreApplicationCoursesQueriesGetCollectionGetCoursesQueryResult>>;
    public coursesGet(studyYear?: number, filterTeacherUid?: string, filterType?: PastExamsHubCoreDomainEnumsCourseType, pageNumber?: number, pageSize?: number, searchText?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (studyYear !== undefined && studyYear !== null) {
            queryParameters = queryParameters.set('StudyYear', <any>studyYear);
        }
        if (filterTeacherUid !== undefined && filterTeacherUid !== null) {
            queryParameters = queryParameters.set('Filter.TeacherUid', <any>filterTeacherUid);
        }
        if (filterType !== undefined && filterType !== null) {
            queryParameters = queryParameters.set('Filter.Type', <any>filterType);
        }
        if (pageNumber !== undefined && pageNumber !== null) {
            queryParameters = queryParameters.set('PageNumber', <any>pageNumber);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (searchText !== undefined && searchText !== null) {
            queryParameters = queryParameters.set('SearchText', <any>searchText);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PastExamsHubCoreApplicationCoursesQueriesGetCollectionGetCoursesQueryResult>('get',`${this.basePath}/Courses`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public coursesPost(body?: PastExamsHubCoreApplicationCoursesCommandsCreateCreateCourseCommand, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public coursesPost(body?: PastExamsHubCoreApplicationCoursesCommandsCreateCreateCourseCommand, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public coursesPost(body?: PastExamsHubCoreApplicationCoursesCommandsCreateCreateCourseCommand, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public coursesPost(body?: PastExamsHubCoreApplicationCoursesCommandsCreateCreateCourseCommand, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Courses`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param uid 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public coursesUidDelete(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommand, observe?: 'body', reportProgress?: boolean): Observable<PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommandResult>;
    public coursesUidDelete(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommand, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommandResult>>;
    public coursesUidDelete(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommand, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommandResult>>;
    public coursesUidDelete(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommand, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling coursesUidDelete.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<PastExamsHubCoreApplicationCoursesCommandsDeleteDeleteCourseCommandResult>('delete',`${this.basePath}/Courses/${encodeURIComponent(String(uid))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param uid 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public coursesUidGet(uid: string, observe?: 'body', reportProgress?: boolean): Observable<PastExamsHubCoreApplicationCoursesQueriesGetSingleGetCourseQueryResult>;
    public coursesUidGet(uid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PastExamsHubCoreApplicationCoursesQueriesGetSingleGetCourseQueryResult>>;
    public coursesUidGet(uid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PastExamsHubCoreApplicationCoursesQueriesGetSingleGetCourseQueryResult>>;
    public coursesUidGet(uid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling coursesUidGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PastExamsHubCoreApplicationCoursesQueriesGetSingleGetCourseQueryResult>('get',`${this.basePath}/Courses/${encodeURIComponent(String(uid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param uid 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public coursesUidPut(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsUpdateUpdateCourseCommand, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public coursesUidPut(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsUpdateUpdateCourseCommand, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public coursesUidPut(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsUpdateUpdateCourseCommand, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public coursesUidPut(uid: string, body?: PastExamsHubCoreApplicationCoursesCommandsUpdateUpdateCourseCommand, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling coursesUidPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/Courses/${encodeURIComponent(String(uid))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
