/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubCoreDomainEnumsFileType = 'Unknown' | 'Document' | 'Image' | 'TextFile';

export const PastExamsHubCoreDomainEnumsFileType = {
    Unknown: 'Unknown' as PastExamsHubCoreDomainEnumsFileType,
    Document: 'Document' as PastExamsHubCoreDomainEnumsFileType,
    Image: 'Image' as PastExamsHubCoreDomainEnumsFileType,
    TextFile: 'TextFile' as PastExamsHubCoreDomainEnumsFileType
};