/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PastExamsHubBaseDomainEnumsRoleType } from './pastExamsHubBaseDomainEnumsRoleType';
import { PastExamsHubCoreDomainEnumsExamPeriodType } from './pastExamsHubCoreDomainEnumsExamPeriodType';
import { PastExamsHubCoreDomainEnumsExamType } from './pastExamsHubCoreDomainEnumsExamType';
import { PastExamsHubCoreDomainEnumsFileType } from './pastExamsHubCoreDomainEnumsFileType';

export interface PastExamsHubCoreApplicationExamSoultionsModelsExamSolutionModel { 
    uid?: string;
    createdDateTimeUtc?: Date;
    ownerUid?: string;
    ownerFirstName?: string;
    ownerLastName?: string;
    ownerRole?: PastExamsHubBaseDomainEnumsRoleType;
    fileType?: PastExamsHubCoreDomainEnumsFileType;
    taskNumber?: number;
    soulutionComment?: string;
    ownerStudyYear?: number;
    gradeCount?: number;
    grade?: number;
    courseName?: string;
    type?: PastExamsHubCoreDomainEnumsExamType;
    periodName?: string;
    periodType?: PastExamsHubCoreDomainEnumsExamPeriodType;
    isEditAndDeleteAllowed?: boolean;
    isAlreadyGraded?: boolean;
    isPositiveGraded?: boolean;
}