/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubCoreDomainEnumsExamPeriodType = 'Unknown' | 'Januar' | 'April' | 'Jun' | 'Jun2' | 'Septembar' | 'Oktobar' | 'Oktobar2' | 'Decembar';

export const PastExamsHubCoreDomainEnumsExamPeriodType = {
    Unknown: 'Unknown' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Januar: 'Januar' as PastExamsHubCoreDomainEnumsExamPeriodType,
    April: 'April' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Jun: 'Jun' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Jun2: 'Jun2' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Septembar: 'Septembar' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Oktobar: 'Oktobar' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Oktobar2: 'Oktobar2' as PastExamsHubCoreDomainEnumsExamPeriodType,
    Decembar: 'Decembar' as PastExamsHubCoreDomainEnumsExamPeriodType
};