/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PastExamsHubCoreApplicationCoursesModelsCourseListModel } from './pastExamsHubCoreApplicationCoursesModelsCourseListModel';
import { PastExamsHubCoreDomainEnumsGenderType } from './pastExamsHubCoreDomainEnumsGenderType';

export interface PastExamsHubCoreApplicationTeachersCommandsUpdateUpdateTeacherCommand { 
    firstName?: string;
    lastName?: string;
    gender?: PastExamsHubCoreDomainEnumsGenderType;
    courses?: Array<PastExamsHubCoreApplicationCoursesModelsCourseListModel>;
}