/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubCoreDomainEnumsStudyType = 'Unknown' | 'OsnovneAkademskeStudije' | 'MasterStudije' | 'DoktorskeStudije';

export const PastExamsHubCoreDomainEnumsStudyType = {
    Unknown: 'Unknown' as PastExamsHubCoreDomainEnumsStudyType,
    OsnovneAkademskeStudije: 'OsnovneAkademskeStudije' as PastExamsHubCoreDomainEnumsStudyType,
    MasterStudije: 'MasterStudije' as PastExamsHubCoreDomainEnumsStudyType,
    DoktorskeStudije: 'DoktorskeStudije' as PastExamsHubCoreDomainEnumsStudyType
};