/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PastExamsHubBaseDomainEnumsRoleType } from './pastExamsHubBaseDomainEnumsRoleType';
import { PastExamsHubCoreApplicationExamSoultionsModelsExamSolutionModel } from './pastExamsHubCoreApplicationExamSoultionsModelsExamSolutionModel';
import { PastExamsHubCoreDomainEnumsExamPeriodType } from './pastExamsHubCoreDomainEnumsExamPeriodType';
import { PastExamsHubCoreDomainEnumsExamType } from './pastExamsHubCoreDomainEnumsExamType';
import { PastExamsHubCoreDomainEnumsFileType } from './pastExamsHubCoreDomainEnumsFileType';

export interface PastExamsHubCoreApplicationExamSoultionsModelsExamSolutionFileModel extends PastExamsHubCoreApplicationExamSoultionsModelsExamSolutionModel { 
    file?: string;
    contentType?: string;
}