/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubBaseDomainEnumsRoleType = 'Unknown' | 'Admin' | 'Student' | 'Teacher';

export const PastExamsHubBaseDomainEnumsRoleType = {
    Unknown: 'Unknown' as PastExamsHubBaseDomainEnumsRoleType,
    Admin: 'Admin' as PastExamsHubBaseDomainEnumsRoleType,
    Student: 'Student' as PastExamsHubBaseDomainEnumsRoleType,
    Teacher: 'Teacher' as PastExamsHubBaseDomainEnumsRoleType
};