/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PastExamsHubCoreDomainEnumsCourseType } from './pastExamsHubCoreDomainEnumsCourseType';
import { PastExamsHubCoreDomainEnumsStudyType } from './pastExamsHubCoreDomainEnumsStudyType';

export interface PastExamsHubCoreApplicationCoursesModelsCourseModel { 
    uid?: string;
    name?: string;
    courseType?: PastExamsHubCoreDomainEnumsCourseType;
    studyType?: PastExamsHubCoreDomainEnumsStudyType;
    lecturerUid?: string;
    lecturerFirstName?: string;
    lecturerLastName?: string;
    studyYear?: number;
    semester?: number;
    espb?: number;
    isEditAndDeleteAllowed?: boolean;
}