/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubCoreDomainEnumsExamType = 'Unkwnon' | 'Pismeni' | 'Usmeni' | 'PismenoUsmeni';

export const PastExamsHubCoreDomainEnumsExamType = {
    Unkwnon: 'Unkwnon' as PastExamsHubCoreDomainEnumsExamType,
    Pismeni: 'Pismeni' as PastExamsHubCoreDomainEnumsExamType,
    Usmeni: 'Usmeni' as PastExamsHubCoreDomainEnumsExamType,
    PismenoUsmeni: 'PismenoUsmeni' as PastExamsHubCoreDomainEnumsExamType
};