/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type PastExamsHubCoreDomainEnumsCourseType = 'Unknown' | 'Obavezni' | 'Izborni';

export const PastExamsHubCoreDomainEnumsCourseType = {
    Unknown: 'Unknown' as PastExamsHubCoreDomainEnumsCourseType,
    Obavezni: 'Obavezni' as PastExamsHubCoreDomainEnumsCourseType,
    Izborni: 'Izborni' as PastExamsHubCoreDomainEnumsCourseType
};